import type { PrismaClient } from "@prisma/client";
import type { DistribuicaoComissao, MovimentoLedgerComissao, PayoutComissao, RepositorioLedgerComissoes } from "../../dominio/ledgerComissoes.js";

export class RepositorioLedgerComissoesPrisma implements RepositorioLedgerComissoes {
  constructor(private prisma: PrismaClient) {}
  async criarDistribuicao(dados: Parameters<RepositorioLedgerComissoes["criarDistribuicao"]>[0]) {
    const existente = await this.buscarDistribuicao(dados.negocioId, dados.origemTipo, dados.origemId); if (existente) return existente;
    const item = await this.prisma.distribuicaoComissao.create({ data: { negocioId: dados.negocioId, origemTipo: dados.origemTipo, origemId: dados.origemId, pedidoId: dados.pedidoId, conversaoId: dados.conversaoId, comissaoLegadaId: dados.comissaoLegadaId, politicaCodigo: dados.politicaCodigo, politicaVersao: dados.politicaVersao, valorBaseEmKwanza: dados.valorBaseEmKwanza, valorComissaoKwanza: dados.valorComissaoKwanza, moeda: dados.moeda, margemEmKwanza: dados.margemEmKwanza, comissaoMaximaKwanza: dados.comissaoMaximaKwanza, explicacaoJson: JSON.stringify(dados.explicacao), participantes: { create: dados.participantes.map((parte) => ({ negocioId: dados.negocioId, parceiroId: parte.parceiroId, papel: parte.papel, pesoBasisPoints: parte.pesoBasisPoints, valorEmKwanza: parte.valorEmKwanza, moeda: dados.moeda })) } }, include: { participantes: true } });
    return this.mapDistribuicao(item);
  }
  async buscarDistribuicao(negocioId: string, origemTipo: string, origemId: string) { const item = await this.prisma.distribuicaoComissao.findUnique({ where: { negocioId_origemTipo_origemId: { negocioId, origemTipo, origemId } }, include: { participantes: true } }); return item ? this.mapDistribuicao(item) : null; }
  async listarDistribuicoes(negocioId: string, parceiroId?: string) { const itens = await this.prisma.distribuicaoComissao.findMany({ where: { negocioId, ...(parceiroId ? { participantes: { some: { parceiroId } } } : {}) }, include: { participantes: true }, orderBy: { criadaEm: "desc" } }); return itens.map((item) => this.mapDistribuicao(item)); }
  async registrarMovimento(dados: Parameters<RepositorioLedgerComissoes["registrarMovimento"]>[0]) { const existente = await this.prisma.movimentoLedgerComissao.findUnique({ where: { idempotencyKey: dados.idempotencyKey } }); if (existente) return this.mapMovimento(existente); const item = await this.prisma.movimentoLedgerComissao.create({ data: { ...dados, metadataJson: JSON.stringify(dados.metadata), metadata: undefined } as never }); return this.mapMovimento(item); }
  async listarMovimentos(negocioId: string, parceiroId?: string) { const itens = await this.prisma.movimentoLedgerComissao.findMany({ where: { negocioId, ...(parceiroId ? { parceiroId } : {}) }, orderBy: { criadoEm: "desc" } }); return itens.map((item) => this.mapMovimento(item)); }
  async criarPayout(dados: Parameters<RepositorioLedgerComissoes["criarPayout"]>[0]) { const existente = await this.prisma.payoutComissao.findUnique({ where: { idempotencyKey: dados.idempotencyKey } }); if (existente) return this.mapPayout(existente); return this.mapPayout(await this.prisma.payoutComissao.create({ data: dados })); }
  async buscarPayout(id: string, negocioId: string) { const item = await this.prisma.payoutComissao.findFirst({ where: { id, negocioId } }); return item ? this.mapPayout(item) : null; }
  async listarPayouts(negocioId: string, parceiroId?: string) { const itens = await this.prisma.payoutComissao.findMany({ where: { negocioId, ...(parceiroId ? { parceiroId } : {}) }, orderBy: { criadoEm: "desc" } }); return itens.map((item) => this.mapPayout(item)); }
  async concluirPayout(id: string, negocioId: string, referencia: string) { const alterado = await this.prisma.payoutComissao.updateMany({ where: { id, negocioId, estado: "EM_PROCESSAMENTO" }, data: { estado: "PAGO", referenciaProvider: referencia, processadoEm: new Date() } }); return alterado.count ? this.buscarPayout(id, negocioId) : null; }
  async falharPayout(id: string, negocioId: string, motivo: string) { const alterado = await this.prisma.payoutComissao.updateMany({ where: { id, negocioId, estado: "EM_PROCESSAMENTO" }, data: { estado: "FALHOU", motivoFalha: motivo, processadoEm: new Date() } }); return alterado.count ? this.buscarPayout(id, negocioId) : null; }
  private json(valor: string) { try { return JSON.parse(valor) as Record<string, unknown>; } catch { return {}; } }
  private mapDistribuicao(item: any): DistribuicaoComissao { return { ...item, explicacao: this.json(item.explicacaoJson), participantes: item.participantes }; }
  private mapMovimento(item: any): MovimentoLedgerComissao { return { ...item, tipo: item.tipo as MovimentoLedgerComissao["tipo"], saldoOrigem: item.saldoOrigem as MovimentoLedgerComissao["saldoOrigem"], saldoDestino: item.saldoDestino as MovimentoLedgerComissao["saldoDestino"], metadata: this.json(item.metadataJson) }; }
  private mapPayout(item: any): PayoutComissao { return { ...item, estado: item.estado as PayoutComissao["estado"] }; }
}
