import { randomUUID } from "node:crypto";
import type { AmostraCreator, CandidaturaCreator, MissaoCreator, OfertaCreator, ParticipacaoMissaoCreator, PerfilCreator, ProgramaAfiliacao, RelacaoAfiliacao, RepositorioCreatorMarketplace, SolicitacaoAfiliacao } from "../../dominio/creatorMarketplace.js";

export class RepositorioCreatorMarketplaceMemoria implements RepositorioCreatorMarketplace {
  private readonly ofertas = new Map<string, OfertaCreator>();
  private readonly candidaturas = new Map<string, CandidaturaCreator>();
  private readonly amostras = new Map<string, AmostraCreator>();
  private readonly participacoes = new Map<string, ParticipacaoMissaoCreator>();
  private readonly perfis = new Map<string, PerfilCreator>();
  private readonly programas = new Map<string, ProgramaAfiliacao>();
  private readonly solicitacoes = new Map<string, SolicitacaoAfiliacao>();
  private readonly relacoes = new Map<string, RelacaoAfiliacao & { produtoOfertaIds: string[] }>();

  async obterPerfilPorConta(contaBizyId: string) { return [...this.perfis.values()].find((item) => item.contaBizyId === contaBizyId) ?? null; }
  async obterPerfilPorId(id: string) { return this.perfis.get(id) ?? null; }
  async salvarPerfil(contaBizyId: string, dados: Parameters<RepositorioCreatorMarketplace["salvarPerfil"]>[1]) { const atual = await this.obterPerfilPorConta(contaBizyId); const agora = new Date(); const item: PerfilCreator = { id: atual?.id ?? randomUUID(), contaBizyId, nomePublico: dados.nomePublico, bio: dados.bio ?? null, avatarUrl: dados.avatarUrl ?? null, localizacao: dados.localizacao ?? null, categorias: dados.categorias, canais: dados.canais, redesSociais: dados.redesSociais ?? {}, estado: dados.estado, nivelVerificacao: atual?.nivelVerificacao ?? "BASICO", termosVersao: dados.termosVersao, termosAceitesEm: dados.termosAceitesEm, criadoEm: atual?.criadoEm ?? agora, atualizadoEm: agora }; this.perfis.set(item.id, item); return item; }
  async garantirPrograma(dados: Parameters<RepositorioCreatorMarketplace["garantirPrograma"]>[0]) { const atual = [...this.programas.values()].find((item) => item.negocioId === dados.negocioId && item.nome === dados.nome); const item: ProgramaAfiliacao = { id: atual?.id ?? randomUUID(), negocioId: dados.negocioId, nome: dados.nome, modalidadeAcesso: dados.modalidadeAcesso, estado: "ATIVO", termosVersao: dados.termosVersao, criterios: dados.criterios, politicaComissao: dados.politicaComissao, politicaConteudo: dados.politicaConteudo }; this.programas.set(item.id, item); return item; }
  async criarSolicitacao(dados: Parameters<RepositorioCreatorMarketplace["criarSolicitacao"]>[0]) { const existente = [...this.solicitacoes.values()].find((item) => item.perfilCreatorId === dados.perfilCreatorId && item.programaId === dados.programaId && item.ofertaId === (dados.ofertaId ?? null) && item.produtoOfertaId === (dados.produtoOfertaId ?? null) && ["PENDENTE", "EM_REVISAO", "APROVADA"].includes(item.estado)); if (existente) throw new Error("CANDIDATURA_EXISTENTE"); const item: SolicitacaoAfiliacao = { id: randomUUID(), perfilCreatorId: dados.perfilCreatorId, programaId: dados.programaId, ofertaId: dados.ofertaId ?? null, produtoOfertaId: dados.produtoOfertaId ?? null, estado: dados.estado, mensagem: dados.mensagem ?? null, motivoDecisao: null, submetidaEm: dados.agora, decididaEm: dados.estado === "APROVADA" ? dados.agora : null, criadoEm: dados.agora, atualizadoEm: dados.agora }; this.solicitacoes.set(item.id, item); return item; }
  async buscarSolicitacao(id: string, contexto: { perfilCreatorId?: string; negocioId?: string }) { const item = this.solicitacoes.get(id) ?? null; const programa = item ? this.programas.get(item.programaId) : null; return item && (!contexto.perfilCreatorId || item.perfilCreatorId === contexto.perfilCreatorId) && (!contexto.negocioId || programa?.negocioId === contexto.negocioId) ? item : null; }
  async listarSolicitacoes(filtros: { perfilCreatorId?: string; negocioId?: string }) { return [...this.solicitacoes.values()].filter((item) => !filtros.perfilCreatorId || item.perfilCreatorId === filtros.perfilCreatorId).filter((item) => !filtros.negocioId || this.programas.get(item.programaId)?.negocioId === filtros.negocioId); }
  async decidirSolicitacao(id: string, negocioId: string, dados: Parameters<RepositorioCreatorMarketplace["decidirSolicitacao"]>[2]) { const item = await this.buscarSolicitacao(id, { negocioId }); if (!item) return null; const atualizado = { ...item, estado: dados.estado, motivoDecisao: dados.motivo ?? null, decididaEm: dados.agora, atualizadoEm: dados.agora }; this.solicitacoes.set(id, atualizado); return atualizado; }
  async ativarRelacao(dados: Parameters<RepositorioCreatorMarketplace["ativarRelacao"]>[0]) { const atual = [...this.relacoes.values()].find((item) => item.perfilCreatorId === dados.perfilCreatorId && item.negocioId === dados.negocioId && item.programaId === dados.programaId); const item: RelacaoAfiliacao & { produtoOfertaIds: string[] } = { id: atual?.id ?? randomUUID(), perfilCreatorId: dados.perfilCreatorId, negocioId: dados.negocioId, programaId: dados.programaId, parceiroComercialId: dados.parceiroComercialId, estado: "ACTIVA", comissao: dados.comissao, termosVersao: dados.termosVersao, iniciadaEm: atual?.iniciadaEm ?? dados.agora, produtoOfertaIds: [...new Set([...(atual?.produtoOfertaIds ?? []), ...dados.produtoOfertaIds])] }; this.relacoes.set(item.id, item); return item; }
  async listarRelacoes(perfilCreatorId: string) { return [...this.relacoes.values()].filter((item) => item.perfilCreatorId === perfilCreatorId); }
  async produtoAutorizado(parceiroComercialId: string, pecaId: string) { const produto = [...this.ofertas.values()].flatMap((item) => item.produtos).find((item) => item.pecaId === pecaId); return Boolean(produto && [...this.relacoes.values()].some((item) => item.parceiroComercialId === parceiroComercialId && item.estado === "ACTIVA" && item.produtoOfertaIds.includes(produto.id))); }

  async criarOferta(dados: Parameters<RepositorioCreatorMarketplace["criarOferta"]>[0]) {
    if ([...this.ofertas.values()].some((item) => item.negocioId === dados.negocioId && item.codigo === dados.codigo)) throw new Error("CODIGO_EM_USO");
    const agora = new Date(); const id = randomUUID();
    const missoes: MissaoCreator[] = dados.missoes.map((item) => ({ ...item, id: randomUUID(), ofertaId: id, negocioId: dados.negocioId, criadaEm: agora, atualizadaEm: agora }));
    const oferta: OfertaCreator = { ...dados, id, publicadaEm: null, criadoEm: agora, atualizadoEm: agora, produtos: dados.produtos.map((item) => ({ ...item, id: randomUUID(), ofertaId: id })), missoes };
    this.ofertas.set(id, oferta); return oferta;
  }
  async buscarOferta(id: string, negocioId?: string) { const item = this.ofertas.get(id) ?? null; return item && (!negocioId || item.negocioId === negocioId) ? item : null; }
  async listarOfertasNegocio(negocioId: string) { return [...this.ofertas.values()].filter((item) => item.negocioId === negocioId).sort((a, b) => b.criadoEm.getTime() - a.criadoEm.getTime()); }
  async listarOfertasPublicadas(agora: Date) { return [...this.ofertas.values()].filter((item) => item.estado === "PUBLICADA" && (!item.iniciaEm || item.iniciaEm <= agora) && (!item.terminaEm || item.terminaEm >= agora)); }
  async publicarOferta(id: string, negocioId: string, publicar: boolean, agora: Date) { const item = await this.buscarOferta(id, negocioId); if (!item) return null; item.estado = publicar ? "PUBLICADA" : "ENCERRADA"; item.publicadaEm = publicar ? agora : item.publicadaEm; item.atualizadoEm = agora; return item; }
  async criarCandidatura(dados: Parameters<RepositorioCreatorMarketplace["criarCandidatura"]>[0]) { const existente = [...this.candidaturas.values()].find((item) => item.ofertaId === dados.ofertaId && item.parceiroId === dados.parceiroId); if (existente) return existente; const agora = new Date(); const item: CandidaturaCreator = { ofertaId: dados.ofertaId, negocioId: dados.negocioId, parceiroId: dados.parceiroId, parceiroNegocioOrigemId: dados.parceiroNegocioOrigemId, id: dados.id ?? randomUUID(), estado: dados.estado ?? "PENDENTE", mensagem: dados.mensagem ?? null, motivoDecisao: null, decididaEm: dados.estado === "APROVADA" ? agora : null, criadoEm: agora, atualizadoEm: agora }; this.candidaturas.set(item.id, item); return item; }
  async buscarCandidatura(id: string, contexto: { negocioId?: string; parceiroIds?: string[] }) { const item = this.candidaturas.get(id) ?? null; if (!item || (contexto.negocioId && item.negocioId !== contexto.negocioId) || (contexto.parceiroIds && !contexto.parceiroIds.includes(item.parceiroId))) return null; return item; }
  async listarCandidaturas(filtros: { negocioId?: string; parceiroIds?: string[] }) { return [...this.candidaturas.values()].filter((item) => !filtros.negocioId || item.negocioId === filtros.negocioId).filter((item) => !filtros.parceiroIds || filtros.parceiroIds.includes(item.parceiroId)); }
  async decidirCandidatura(id: string, negocioId: string, dados: { estado: "APROVADA" | "REJEITADA"; motivo?: string | null; agora: Date }) { const item = await this.buscarCandidatura(id, { negocioId }); if (!item) return null; item.estado = dados.estado; item.motivoDecisao = dados.motivo ?? null; item.decididaEm = dados.agora; item.atualizadoEm = dados.agora; return item; }
  async solicitarAmostra(candidatura: CandidaturaCreator, observacao?: string | null) { if ([...this.amostras.values()].some((item) => item.candidaturaId === candidatura.id)) throw new Error("AMOSTRA_EXISTENTE"); const agora = new Date(); const item: AmostraCreator = { id: randomUUID(), candidaturaId: candidatura.id, negocioId: candidatura.negocioId, parceiroId: candidatura.parceiroId, estado: "SOLICITADA", observacao: observacao ?? null, trackingEnvio: null, criadaEm: agora, atualizadaEm: agora }; this.amostras.set(item.id, item); const oferta = this.ofertas.get(candidatura.ofertaId); if (oferta) oferta.stockAmostras -= 1; return item; }
  async listarAmostras(filtros: { negocioId?: string; parceiroIds?: string[] }) { return [...this.amostras.values()].filter((item) => !filtros.negocioId || item.negocioId === filtros.negocioId).filter((item) => !filtros.parceiroIds || filtros.parceiroIds.includes(item.parceiroId)); }
  async aceitarMissao(dados: { missaoId: string; candidaturaId: string; parceiroId: string }) { const existente = [...this.participacoes.values()].find((item) => item.missaoId === dados.missaoId && item.parceiroId === dados.parceiroId); if (existente) return existente; const item: ParticipacaoMissaoCreator = { ...dados, id: randomUUID(), estado: "ACEITE", progresso: {}, aceiteEm: new Date(), concluidaEm: null }; this.participacoes.set(item.id, item); return item; }
  async listarParticipacoes(parceiroIds: string[]) { return [...this.participacoes.values()].filter((item) => parceiroIds.includes(item.parceiroId)); }
}
