ALTER TABLE "ComentarioRecebido" ADD COLUMN IF NOT EXISTS "perfilUsuarioJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ComentarioRecebido" ADD COLUMN IF NOT EXISTS "eventoBrutoJson" TEXT NOT NULL DEFAULT '{}';

ALTER TABLE "Negocio" ADD COLUMN IF NOT EXISTS "perfil360Json" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Negocio" ADD COLUMN IF NOT EXISTS "dadosOperacionaisJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Negocio" ADD COLUMN IF NOT EXISTS "fontesDadosJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Negocio" ADD COLUMN IF NOT EXISTS "ultimoEnriquecimentoEm" TIMESTAMP(3);

ALTER TABLE "ClienteGlobal" ADD COLUMN IF NOT EXISTS "perfil360Json" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteGlobal" ADD COLUMN IF NOT EXISTS "identidadesDigitaisJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteGlobal" ADD COLUMN IF NOT EXISTS "fontesDadosJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteGlobal" ADD COLUMN IF NOT EXISTS "ultimoEnriquecimentoEm" TIMESTAMP(3);

ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "perfil360Json" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "identidadesDigitaisJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "fontesDadosJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "perfilComercialJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "sinaisRelacionamentoJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "dadosCapturaJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "ClienteNegocio" ADD COLUMN IF NOT EXISTS "ultimoEnriquecimentoEm" TIMESTAMP(3);
