import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");

describe("Bizy Learning frontend", () => {
  it("liga Learning publico, backoffice Team e chat interno", () => {
    const pagina = source("src/projetos/learning/paginas/Learning.tsx");
    const produto = source("src/projetos/learning/paginas/ProdutoLearning.tsx");
    const api = source("src/projetos/learning/api.ts");
    const apiPublica = source("src/projetos/learning/apiPublica.ts");
    const rotas = source("src/rotasApp.tsx");
    const navegacaoTeam = source("src/projetos/learning/team/LearningTeamNavigation.tsx");

    expect(rotas).toContain('caminho: "/learning"');
    expect(rotas).toContain('caminho: "/learning/produtos/:slug"');
    expect(rotas).toContain('caminho: "/learning/:slug"');
    expect(rotas).toContain('caminho: "/app/learning"');
    expect(rotas).toContain('caminho: "/app/learning/programas"');
    expect(rotas).toContain('caminho: "/app/learning/avaliacoes"');
    expect(rotas).toContain('caminho: "/app/learning/configuracoes"');
    expect(navegacaoTeam).toContain("NavegacaoLearningTeam");
    expect(navegacaoTeam).toContain("resolverAreaLearningTeam");
    expect(navegacaoTeam).toContain('rotulo: "Certificados"');
    expect(navegacaoTeam).toContain('rotulo: "Biblioteca"');
    expect(api).toContain("/publico/learning");
    expect(api).toContain("/publico/learning/perfis/${encodeURIComponent(slug)}");
    expect(api).toContain("PerfilLearningPublico");
    expect(api).toContain("perfisPublicos");
    expect(api).toContain("/learning/team/resumo");
    expect(api).toContain("/learning/team/chat");
    expect(api).toContain("/learning/team/chat/mensagens");
    expect(api).toContain("/learning/team/programas/${encodeURIComponent(slug)}/atribuir");
    expect(api).toContain("/learning/team/cohorts");
    expect(api).toContain("/learning/team/programas/${encodeURIComponent(slug)}/cohorts");
    expect(api).toContain("/learning/team/cohorts/${encodeURIComponent(id)}/presencas");
    expect(api).toContain("/learning/team/comunidades");
    expect(api).toContain("/learning/team/programas/${encodeURIComponent(slug)}/comunidades");
    expect(api).toContain("/learning/team/comunidades/${encodeURIComponent(id)}/posts");
    expect(api).toContain("/learning/team/moderacao");
    expect(api).toContain("/learning/team/moderacao/denuncias");
    expect(api).toContain("/learning/team/moderacao/${encodeURIComponent(id)}");
    expect(api).toContain("/learning/team/compras/${encodeURIComponent(id)}/ajustar");
    expect(api).toContain("/learning/entitlements/${encodeURIComponent(id)}/revogar");
    expect(api).toContain("ajustarCompraLearningTeam");
    expect(api).toContain("revogarEntitlementLearning");
    expect(api).toContain("visualizacoesPublicas");
    expect(api).toContain("ctasCheckoutLearning");
    expect(apiPublica).toContain("obterProdutoLearning");
    expect(apiPublica).toContain("registrarEventoPublicoLearning");
    expect(apiPublica).toContain("/publico/learning/produtos/${encodeURIComponent(slug)}");
    expect(apiPublica).toContain("/publico/learning/eventos");
    expect(api).toContain("AtribuicaoLearning");
    expect(api).toContain("CohortLearning");
    expect(api).toContain("ComunidadeLearning");
    expect(api).toContain("CasoModeracaoLearning");
    expect(api).toContain("ChatInternoLearning");
    expect(pagina).toContain("Chat interno do Learning");
    expect(pagina).toContain("Atribuições e formação obrigatória");
    expect(pagina).toContain("Cohorts, lives e presenças");
    expect(pagina).toContain("Comunidades e memberships");
    expect(pagina).toContain("Governança e moderação Learning");
    expect(pagina).toContain("abrirCohortLearningTeam");
    expect(pagina).toContain("registrarPresencaCohortLearning");
    expect(pagina).toContain("criarComunidadeLearningTeam");
    expect(pagina).toContain("publicarPostComunidadeLearning");
    expect(pagina).toContain("denunciarConteudoLearning");
    expect(pagina).toContain("decidirModeracaoLearning");
    expect(pagina).toContain("atribuirProgramaLearningTeam");
    expect(pagina).toContain("Como funciona a tua evolução");
    expect(pagina).toContain("Formatos de Aprendizagem");
    expect(pagina).toContain("PaginaPerfilLearning");
    expect(pagina).toContain("obterPerfilLearning");
    expect(pagina).toContain("PerfilLearningPublicoCard");
    expect(pagina).toContain("Aceder");
    expect(pagina).toContain("Visualizações públicas");
    expect(pagina).toContain("Pré-visualizações");
    expect(pagina).toContain("Reembolsar e revogar");
    expect(pagina).toContain("Revogar acesso");
    expect(pagina).toContain("enviarMensagemChatLearning");
    expect(pagina).toContain("listarChatInternoLearning");
    expect(pagina).toContain("sem misturar com WhatsApp ou atendimento externo");
    expect(pagina).toContain("DECISAO");
    expect(pagina).toContain("COHORT");
    expect(produto).toContain("PaginaProdutoLearning");
    expect(produto).toContain("Preview seguro");
    expect(produto).toContain("Política de acesso");
    expect(produto).toContain("Comprovativo digital aceite");
    expect(produto).toContain("conteudoPremiumProtegido");
    expect(produto).toContain("CTA_CHECKOUT");
    expect(produto).toContain("CTA_INSCRICAO");
  });
});
