import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const homeSource = () => readFileSync(resolve(process.cwd(), "src/paginas/Home.tsx"), "utf8");
const ctaSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/cta-with-text-marquee.tsx"), "utf8");
const footerSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/footer-column.tsx"), "utf8");
const howItWorksSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/how-it-works.tsx"), "utf8");
const pricingSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/single-pricing-card-1.tsx"), "utf8");
const borderTrailSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/border-trail.tsx"), "utf8");
const promptFontSource = () => readFileSync(resolve(process.cwd(), "src/lib/prompt-font.ts"), "utf8");
const faqSectionSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/faqsection.tsx"), "utf8");
const authPageSource = () => readFileSync(resolve(process.cwd(), "src/components/ui/auth-page.tsx"), "utf8");
const loginSource = () => readFileSync(resolve(process.cwd(), "src/paginas/Login.tsx"), "utf8");

describe("landing page Bizy", () => {
  it("usa hero live-commerce com imagem local, marquee e shadcn", () => {
    const source = homeSource();
    const cta = ctaSource();
    const footer = footerSource();
    const howItWorks = howItWorksSource();
    const pricing = pricingSource();
    const borderTrail = borderTrailSource();
    const promptFont = promptFontSource();
    const faqSection = faqSectionSource();
    const authPage = authPageSource();
    const login = loginSource();

    expect(source).toContain("framer-motion");
    expect(source).toContain("useReducedMotion");
    expect(source).toContain("MotionDiv");
    expect(source).toContain("LiveCommerceHero");
    expect(source).toContain("CORES_LOGO_BIZY_ESCURA");
    expect(source).toContain("<LogoBizy cores={CORES_LOGO_BIZY_ESCURA}");
    expect(source).toContain("BizyFeaturesSection");
    expect(source).toContain("CTAWithTextMarquee");
    expect(source).toContain("Footer4Col");
    expect(source).toContain("Pricing");
    expect(source).toContain("FAQSection");
    expect(source).toContain("AvatarStack");
    expect(source).toContain("StatsMarquee");
    expect(source).toContain("HowItWorks");
    expect(source).toContain("@/components/ui/marquee");
    expect(source).toContain("bizy-live-commerce-hero.png");
    expect(source).toContain("@/components/ui/avatar");
    expect(source).toContain("@/components/ui/badge");
    expect(source).toContain("@/components/ui/button");
    expect(source).toContain("@/components/ui/item");
    expect(source).toContain("@/components/ui/navigation-menu");
    expect(source).toContain("@/components/ui/cta-with-text-marquee");
    expect(source).toContain("@/components/ui/footer-column");
    expect(source).toContain("@/components/ui/how-it-works");
    expect(source).toContain("@/components/ui/single-pricing-card-1");
    expect(source).toContain("@/components/ui/faqsection");
    expect(source).toContain("NavigationMenuTrigger");
    expect(source).toContain("ItemMedia");
    expect(source).toContain("Venda pelo");
    expect(source).toContain("CRM+ para social commerce");
    expect(source).toContain("PROMPT_FONT_FAMILY");
    expect(source).not.toContain("DM Sans");
    expect(promptFont).toContain("ui-sans-serif, system-ui");
    expect(promptFont).not.toContain("DM Sans");
    expect(howItWorks).toContain("PROMPT_FONT_FAMILY");
    expect(pricing).toContain("PROMPT_FONT_FAMILY");
    expect(cta).toContain("PROMPT_FONT_FAMILY");
    expect(howItWorks).toContain("Como o Bizy organiza a tua operação");
    expect(howItWorks).toContain("Montar loja e regras");
    expect(howItWorks).toContain("Publicar produtos e canais");
    expect(howItWorks).toContain("Atender, entregar e medir");
    expect(howItWorks).toContain("StepCard");
    expect(howItWorks).toContain("stepsData");
    expect(pricing).toContain("Preços em Kwanza");
    expect(pricing).toContain("Mensal");
    expect(pricing).toContain("Anual");
    expect(pricing).toContain("24 900 Kz");
    expect(pricing).toContain("19 900 Kz");
    expect(pricing).toContain("BorderTrail");
    expect(borderTrail).toContain("offsetDistance");
    expect(cta).toContain("Começa com uma loja organizada");
    expect(cta).toContain("Começar agora");
    expect(cta).toContain("VerticalMarquee");
    expect(faqSection).toContain("faqsLeft");
    expect(faqSection).toContain("faqsRight");
    expect(faqSection).toContain("Accordion");
    expect(faqSection).toContain("Browse All FAQs");
    expect(faqSection).toContain("ArrowRight");
    expect(faqSection).toContain("justify-center");
    expect(faqSection).toContain("text-left md:grid-cols-2");
    expect(faqSection).toContain("fontFamily: PROMPT_FONT_FAMILY");
    expect(source).toContain("Dúvidas sobre o Bizy");
    expect(source).toContain("Como o WhatsApp oficial entra na operação?");
    expect(source).toContain("Ver preços");
    expect(footer).toContain("CRM+ para lojas, criadores e afiliados");
    expect(footer).toContain("CORES_LOGO_BIZY_ESCURA");
    expect(footer).toContain("<LogoBizy cores={CORES_LOGO_BIZY_ESCURA}");
    expect(footer).toContain("Atendimento WhatsApp");
    expect(footer).toContain("Luanda, Angola");
    expect(source).toContain("perguntasOperacao");
    expect(source).toContain("Jovem empreendedora em live no TikTok vendendo roupas");
    expect(source).toContain("Pedidos com controlo");
    expect(source).toContain("WhatsApp oficial");
    expect(source).toContain("sm:text-4xl md:text-5xl lg:text-6xl");
    expect(source).not.toContain("lg:text-7xl");
    expect(cta).toContain('style={{ color: "#000000" }}');
    expect(cta).toContain("md:text-5xl lg:text-6xl");
    expect(cta).not.toContain("lg:text-7xl");
    expect(cta).not.toContain("xl:text-7xl");
    expect(howItWorks).toContain("sm:text-4xl");
    expect(howItWorks).not.toContain("sm:text-5xl");
    expect(pricing).toContain("sm:text-4xl");
    expect(pricing).not.toContain("sm:text-5xl");
    expect(source).not.toContain('src="/hero-mockup.png"');
    expect(source).not.toContain("home-operacao-ao-vivo");
    expect(existsSync(resolve(process.cwd(), "public/bizy-live-commerce-hero.png"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/cta-with-text-marquee.tsx"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/footer-column.tsx"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/how-it-works.tsx"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/single-pricing-card-1.tsx"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/border-trail.tsx"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/lib/prompt-font.ts"))).toBe(true);
    expect(existsSync(resolve(process.cwd(), "src/components/ui/faqsection.tsx"))).toBe(true);

    [source, cta, footer, howItWorks, pricing, faqSection, authPage, login].forEach((conteudo) => {
      expect(conteudo).not.toContain("#971A58");
      expect(conteudo).not.toContain("151,26,88");
      expect(conteudo).not.toContain("#21141d");
      expect(conteudo).not.toContain("#fbfafb");
    });
  });
});
