import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");

describe("login Bizy", () => {
  it("usa animated-tabs 21st sem icone de brilho na identidade", () => {
    const login = source("src/paginas/Login.tsx");
    const animatedTabs = source("src/components/ui/animated-tabs.tsx");
    const authPage = source("src/components/ui/auth-page.tsx");

    expect(login).toContain("@/components/ui/auth-page");
    expect(login).toContain("AuthPage");
    expect(login).toContain("AuthSeparator");
    expect(login).toContain("GoogleIcon");
    expect(login).toContain('visualImage="/bizy-login-team.png"');
    expect(login).toContain("visualImageAlt");
    expect(login).toContain('useState("")');
    expect(login).toContain("{mensagem ? (");
    expect(login).toContain('type FluxoIdentidade = "criar" | "entrar"');
    expect(login).toContain("fluxoIdentidade");
    expect(login).toContain("Criar conta");
    expect(login).toContain("Entrar");
    expect(login).toContain("Criar conta com Gmail");
    expect(login).toContain("Entrar com Gmail");
    expect(login).toContain("Criar conta com telefone");
    expect(login).toContain("Criar perfil com login estudantil");
    expect(login).toContain("Entrar com login estudantil");
    expect(login).toContain('destinoAposAutenticacao');
    expect(login).toContain('estaCriandoConta ? "/onboarding" : "/app"');
    expect(login).toContain("bg-[#050706]/");
    expect(login).not.toContain("bg-[#07100d]/82");
    expect(login).toContain("border-white/12");
    expect(login).toContain("border-white/16");
    expect(login).toContain("active:border-[#d8ff72]");
    expect(login).toContain("--animated-tabs-active-bg");
    expect(login).toContain("--animated-tabs-active-ring");
    expect(login).not.toContain("borderColor: \"#d8ff72\"");
    expect(login).not.toContain('"--animated-tabs-active-ring": "#d8ff72"');
    expect(login).not.toContain("border border-[#d8ff72]");
    expect(login).not.toContain("hover:border-[#d8ff72]");
    expect(login).not.toContain("sideTitle=");
    expect(login).not.toContain("sideDescription=");
    expect(login).not.toContain("contextItems=");
    expect(login).not.toContain("quote=");
    expect(login).toContain("@/components/ui/animated-tabs");
    expect(login).toContain("AnimatedTabs");
    expect(login).not.toContain("rounded-[2rem]");
    expect(login).not.toContain("Sparkles");
    expect(authPage).toContain("FloatingPaths");
    expect(authPage).toContain("lg:grid-cols-2");
    expect(authPage).toContain("bg-[#050706]");
    expect(authPage).not.toContain("bg-[#07100d]");
    expect(authPage).toContain("border-r border-white/10");
    expect(authPage).not.toContain("border-r border-[#d8ff72]");
    expect(authPage).not.toContain("lg:bg-[#FBFDF8]");
    expect(authPage).toContain("visualImage");
    expect(authPage).toContain("bizy-login-team.png");
    expect(authPage).toContain("object-cover");
    expect(authPage).toContain("bg-black/32");
    expect(authPage).toContain("text-[#d8ff72]");
    expect(authPage).not.toContain("{sideTitle}");
    expect(authPage).not.toContain("{sideDescription}");
    expect(authPage).not.toContain("contextItems.map");
    expect(authPage).not.toContain("blockquote");
    expect(authPage).toContain("strokeDasharray");
    expect(authPage).toContain("useReducedMotion");
    expect(authPage).toContain("motion.path");
    expect(animatedTabs).toContain("framer-motion");
    expect(animatedTabs).toContain("layoutId=\"animated-tabs-active\"");
    expect(animatedTabs).toContain("--animated-tabs-active-bg");
  });
});
