import { z } from "zod";
import type { ModuloHttp } from "../../../../infra/http/modulos/ModuloHttp.js";
import { exigirContaAutenticada } from "../../../commerce/infra/http/segurancaContaBizy.js";
import { exigirAcessoComercial } from "../../../../infra/http/contextoComercial.js";

export const moduloConfiancaCommerce: ModuloHttp = { nome: "confianca-commerce", descricao: "Avaliacoes verificadas, risco e proteccao do comprador.", registrar(app, contexto) {
  app.post("/conta/avaliacoes", async (request, reply) => { const acesso = await exigirContaAutenticada(contexto, request, reply); if (!acesso) return; const dados = z.object({ pedidoId: z.string().uuid(), pecaId: z.string().uuid().nullable().optional(), notaProduto: z.number().int().min(1).max(5), notaEntrega: z.number().int().min(1).max(5), notaSeller: z.number().int().min(1).max(5), titulo: z.string().trim().max(120).nullable().optional(), comentario: z.string().trim().max(3000).nullable().optional() }).parse(request.body ?? {}); try { const avaliacao = await contexto.confiancaCommerce.criarAvaliacao(acesso.conta.id, dados); return avaliacao ? reply.code(201).send(avaliacao) : reply.code(404).send({ erro: "PEDIDO_NAO_ENCONTRADO" }); } catch (erro) { return reply.code(409).send({ erro: erro instanceof Error ? erro.message : "AVALIACAO_INVALIDA" }); } });
  app.get("/publico/avaliacoes", async (request) => { const filtros = z.object({ negocioId: z.string().uuid().optional(), pecaId: z.string().uuid().optional() }).parse(request.query ?? {}); return { avaliacoes: await contexto.confiancaCommerce.listarAvaliacoesPublicas(filtros) }; });
  app.post("/conta/protecao", async (request, reply) => { const acesso = await exigirContaAutenticada(contexto, request, reply); if (!acesso) return; const dados = z.object({ compraId: z.string().uuid(), pedidoId: z.string().uuid().nullable().optional(), tipo: z.enum(["NAO_ENTREGUE", "DIVERGENTE", "DANIFICADO", "REEMBOLSO", "FRAUDE"]), descricao: z.string().trim().min(10).max(3000), evidencias: z.array(z.string().trim().max(500)).max(20).optional() }).parse(request.body ?? {}); const caso = await contexto.confiancaCommerce.abrirProtecao(acesso.conta.id, dados); return caso ? reply.code(201).send(caso) : reply.code(404).send({ erro: "COMPRA_NAO_ENCONTRADA" }); });
  app.get("/conta/protecao", async (request, reply) => { const acesso = await exigirContaAutenticada(contexto, request, reply); if (!acesso) return; return { casos: await contexto.confiancaCommerce.listarProtecao(acesso.conta.id) }; });
  app.post("/market/risco/analisar", async (request, reply) => { const acesso = await exigirAcessoComercial(contexto, request, reply, { permissao: "pagamentos:gerir", modulo: "market", mensagemPermissao: "Sem permissao para analisar risco.", mensagemModulo: "Market desativado." }); if (!acesso) return; const dados = z.object({ contaBizyId: z.string().uuid().nullable().optional(), parceiroId: z.string().uuid().nullable().optional(), pedidoId: z.string().uuid().nullable().optional(), payoutId: z.string().uuid().nullable().optional(), sinais: z.record(z.union([z.boolean(), z.number()])), evidencias: z.array(z.string().max(500)).max(30).optional() }).parse(request.body ?? {}); return contexto.confiancaCommerce.analisarRisco({ ...dados, negocioId: acesso.negocio.id, sinais: dados.sinais }); });
  app.get("/market/risco/casos", async (request, reply) => { const acesso = await exigirAcessoComercial(contexto, request, reply, { permissao: "pagamentos:gerir", modulo: "market", mensagemPermissao: "Sem permissao para consultar risco.", mensagemModulo: "Market desativado." }); if (!acesso) return; return { casos: await contexto.confiancaCommerce.listarCasos(acesso.negocio.id) }; });
  app.patch("/market/risco/casos/:id", async (request, reply) => { const acesso = await exigirAcessoComercial(contexto, request, reply, { permissao: "pagamentos:gerir", modulo: "market", mensagemPermissao: "Sem permissao para decidir risco.", mensagemModulo: "Market desativado." }); if (!acesso) return; const { id } = z.object({ id: z.string().uuid() }).parse(request.params); const { decisao } = z.object({ decisao: z.string().trim().min(3).max(1000) }).parse(request.body ?? {}); const caso = await contexto.confiancaCommerce.decidirCaso(id, acesso.negocio.id, { decisao, responsavelId: acesso.usuario.id }); return caso ?? reply.code(404).send({ erro: "CASO_NAO_ENCONTRADO" }); });
} };
