import { z } from "zod";
import type { ModuloHttp } from "../../../../infra/http/modulos/ModuloHttp.js";
import { exigirContaAutenticada, obterTokenCarrinho, resolverContaAutenticada } from "../../../commerce/infra/http/segurancaContaBizy.js";
import { exigirAcessoComercial } from "../../../../infra/http/contextoComercial.js";

const Item = z.object({ slugLoja: z.string().trim().min(1).max(160), codigoPeca: z.string().trim().min(1).max(160), varianteSelecionada: z.record(z.string()).nullable().optional(), quantidade: z.number().int().min(1).max(99) });
export const moduloCarrinhosPartilhaveis: ModuloHttp = { nome: "carrinhos-partilhaveis", descricao: "Carrinhos publicos e live afiliada.", registrar(app, contexto) {
  app.get("/creator/carrinhos/dados", async (request, reply) => { const acesso = await exigirContaAutenticada(contexto, request, reply); if (!acesso) return; return { carrinhos: await contexto.carrinhosPartilhaveis.listar(acesso.conta.id) }; });
  app.post("/creator/carrinhos/criar", async (request, reply) => { const acesso = await exigirContaAutenticada(contexto, request, reply); if (!acesso) return; const dados = z.object({ parceiroId: z.string().uuid().nullable().optional(), criadoPorTipo: z.enum(["AFILIADO", "VENDEDOR", "COMPRADOR", "CRIADOR", "CAMPANHA", "ORCAMENTO"]), titulo: z.string().trim().min(3).max(180), descricao: z.string().trim().max(1000).nullable().optional(), campanhaId: z.string().max(180).nullable().optional(), liveId: z.string().max(180).nullable().optional(), expiraEm: z.coerce.date().nullable().optional(), itens: z.array(Item).min(1).max(100) }).parse(request.body ?? {}); try { return reply.code(201).send(await contexto.carrinhosPartilhaveis.criar(acesso.conta.id, dados)); } catch (erro) { return reply.code(400).send({ erro: erro instanceof Error ? erro.message : "CARRINHO_INVALIDO" }); } });
  app.get("/publico/carrinhos/:codigo", async (request, reply) => { const { codigo } = z.object({ codigo: z.string().trim().min(4).max(80) }).parse(request.params); const item = await contexto.carrinhosPartilhaveis.obterPublico(codigo); return item ?? reply.code(404).send({ erro: "CARRINHO_NAO_ENCONTRADO" }); });
  app.post("/publico/carrinhos/:codigo/importar", async (request, reply) => { const { codigo } = z.object({ codigo: z.string().trim().min(4).max(80) }).parse(request.params); const acesso = await resolverContaAutenticada(contexto, request); const resultado = await contexto.carrinhosPartilhaveis.importar(codigo, acesso?.conta.id ?? null, obterTokenCarrinho(request)); return resultado ?? reply.code(404).send({ erro: "CARRINHO_NAO_ENCONTRADO" }); });
  app.post("/market/lives/:liveId/destaques", async (request, reply) => { const acesso = await exigirAcessoComercial(contexto, request, reply, { permissao: "afiliados:gerir", modulo: "market", mensagemPermissao: "Sem permissao para destacar produtos.", mensagemModulo: "Market desativado." }); if (!acesso) return; const { liveId } = z.object({ liveId: z.string().min(1).max(180) }).parse(request.params); const dados = z.object({ pecaId: z.string().uuid(), variantePecaId: z.string().uuid().nullable().optional(), hostParceiroId: z.string().uuid().nullable().optional(), carrinhoPartilhavelId: z.string().uuid().nullable().optional() }).parse(request.body ?? {}); try { const destaque = await contexto.carrinhosPartilhaveis.destacarLive(acesso.negocio.id, { liveId, ...dados }); return destaque ? reply.code(201).send(destaque) : reply.code(404).send({ erro: "LIVE_OU_PRODUTO_NAO_ENCONTRADO" }); } catch (erro) { return reply.code(400).send({ erro: erro instanceof Error ? erro.message : "DESTAQUE_INVALIDO" }); } });
  app.get("/publico/lives/:liveId/destaque", async (request, reply) => { const { liveId } = z.object({ liveId: z.string().min(1).max(180) }).parse(request.params); return await contexto.carrinhosPartilhaveis.obterDestaqueLive(liveId) ?? reply.code(404).send({ erro: "DESTAQUE_NAO_ENCONTRADO" }); });
} };
