import { requisitarApi } from "../../../api";
import { guardarCarrinhoCheckoutBizy, guardarTokenCarrinhoCheckoutBizy, obterTokenCarrinhoCheckoutBizy } from "./checkoutUnificado";

export interface CarrinhoPartilhavelPublico { codigo: string; titulo: string; descricao: string | null; criadoPorTipo: string; parceiroId: string | null; liveId: string | null; itens: Array<{ slugLoja: string; codigoPeca: string; varianteSelecionada?: Record<string, string>; quantidade: number; nomeProduto?: string; nomeFornecedor?: string; precoUnitarioEmKwanza?: number; fotoUrl?: string | null }> }
export interface CarrinhoPartilhavelCreator { id: string; codigo: string; titulo: string; descricao: string | null; estado: string; visualizacoes: number; importacoes: number; criadoEm: string }
export function obterCarrinhoPartilhavel(codigo: string): Promise<CarrinhoPartilhavelPublico> { return requisitarApi(`/publico/carrinhos/${encodeURIComponent(codigo)}`, {}, false); }
export function listarCarrinhosCreator(): Promise<{ carrinhos: CarrinhoPartilhavelCreator[] }> { return requisitarApi("/creator/carrinhos/dados", {}, false); }
export function criarCarrinhoCreator(dados: { parceiroId?: string | null; titulo: string; descricao?: string | null; itens: Array<{ slugLoja: string; codigoPeca: string; quantidade: number }> }): Promise<CarrinhoPartilhavelCreator> { return requisitarApi("/creator/carrinhos/criar", { method: "POST", body: { ...dados, criadoPorTipo: "CRIADOR" } }, false); }
export async function importarCarrinhoPartilhavel(codigo: string) { const token = obterTokenCarrinhoCheckoutBizy(); const resposta = await requisitarApi<{ carrinho: { itens: Array<{ id: string; slugLoja: string; codigoPeca: string; nomeProduto: string; nomeFornecedor: string; quantidade: number; precoUnitarioEmKwanza: number; fotoUrl: string | null; urlProduto: string | null; urlLoja: string | null; selecaoVariante: Record<string, string>; origem: string }> }; token: string | null }>(`/publico/carrinhos/${encodeURIComponent(codigo)}/importar`, { method: "POST", headers: token ? { "X-Bizy-Cart-Token": token } : {} }, false); if (resposta.token) guardarTokenCarrinhoCheckoutBizy(resposta.token); guardarCarrinhoCheckoutBizy(resposta.carrinho.itens.map((item) => ({ id: item.id, slugLoja: item.slugLoja, codigoProduto: item.codigoPeca, nomeProduto: item.nomeProduto, nomeFornecedor: item.nomeFornecedor, quantidade: item.quantidade, precoUnitarioEmKwanza: item.precoUnitarioEmKwanza, fotoUrl: item.fotoUrl, urlProduto: item.urlProduto, urlLoja: item.urlLoja, variantes: item.selecaoVariante, origem: item.origem, adicionadoEm: new Date().toISOString() }))); return resposta.carrinho; }
